services:
  - type: web
    name: nostai-bot
    env: python
    plan: free
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
